export const POST_POEM_SUCCESS = 'POST_POEM_SUCCESS';
export const POST_POEM_FAILURE = 'POST_POEM_FAILURE';
export const GET_POEMS_SUCCESS = 'GET_POEMS_SUCCESS';
export const GET_POEMS_FAILURE = 'GET_POEMS_FAILURE';
